services:
#  app:
#    image: 'docker.io/library/debtors-management'
#    ports:
#      - "8080:8080"
#    environment:
#      -
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/