services:
  app:
    image: 'docker.io/library/debtors-management:0.0.1-SNAPSHOT'
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=debtors-management
      - MANAGEMENT_ENDPOINT_METRICS_ACCESS=read_only
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/DEBTORS-DB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE.DRIVER-CLASS-NAME=org.postgresql.Driver

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/SONAR-DB
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: root
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data: