services:
#  app:
#    image: 'docker.io/library/debtors-management'
#    ports:
#      - "8080:8080"
#    environment:
#      -

  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/SONAR-DB
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: root
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data: