name: Dependabot Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run dependabot
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          directory: '/'
          package-ecosystem: "maven"
          versioning-strategy: increase


